// mwcc-version: 1.2/base
#include "types.h"

// ov042: map scene tables (a scene record, its entry list, the id grid, the static map objects).
// Generated by pipeline_wip/smallov2_work/gen.py from the original image; the definition order below
// reproduces the original data/bss order (mwcc size heapsort) and the __sinit order.

// 12-byte vector with a copy constructor (so it is passed by address of a copy)
struct Unk_020b4f8c_Vec {
    s32 x, y, z;
    Unk_020b4f8c_Vec(s32 a, s32 b, s32 c) {
        x = a;
        y = b;
        z = c;
    }
    Unk_020b4f8c_Vec(const Unk_020b4f8c_Vec &o) {
        x = o.x;
        y = o.y;
        z = o.z;
    }
};

// 0x1c-byte map object: constructor 0x020b4f8c, destructor 0x020b4fc0 (both in main)
struct Unk_020b4f8c {
    u8 pad[0x1c];
    Unk_020b4f8c(u8 id, Unk_020b4f8c_Vec v, u32 w, s16 s, u8 p, u8 q, s16 r, u8 t);
    ~Unk_020b4f8c();
};

struct Unk_ov042_Entry {  // one list of the scene: kind 2 = ids (u32), 1 and 0 = 20-byte records
    u8 kind;
    u8 count;
    u16 pad;
    void *list;
};

struct Unk_ov042_Head {
    u32 count;
    Unk_ov042_Entry *entries;
};

struct Unk_ov042_Grid {  // width x height ids
    u32 *ids;
    u8 width;
    u8 height;
    u16 pad;
};

struct Unk_ov042_Objs {
    Unk_020b4f8c *objs;
    u32 count;
};

struct Unk_ov042_Rec {
    u32 w[5];
};

struct Unk_ov042_Scene {  // 24 bytes; main's table data_020e4280 points to it
    Unk_ov042_Head *head;
    s32 unk_04;
    Unk_ov042_Grid *grid;
    Unk_ov042_Objs *objs;
    s32 unk_10;
    s32 unk_14;
};

extern u8 data_ov004_0224f2d4;  // copied into the entry table by __sinit
extern u32 data_ov004_0224f2d8[];

// Declarations for data defined further down (definition order sets the data layout)
extern Unk_ov042_Rec data_ov042_02258b00[2];
extern Unk_ov042_Objs data_ov042_02258ab4;
extern u32 data_ov042_02258aa0[1];
extern Unk_ov042_Entry data_ov042_02258ae8[3];
extern Unk_ov042_Scene data_ov042_02258ad0;
extern Unk_ov042_Grid data_ov042_02258aa4;
extern Unk_ov042_Rec data_ov042_02258abc[1];
extern Unk_020b4f8c data_ov042_02258b58[2];
extern Unk_ov042_Head data_ov042_02258aac;

Unk_ov042_Rec data_ov042_02258b00[2] = {
    {0xf00075, 0xc00000, 0x80000000, 0, 0xd010},
    {0x1100074, 0xc00000, 0x80000000, 0, 0xd00f},
};

Unk_ov042_Objs data_ov042_02258ab4 = {data_ov042_02258b58, 2};

u32 data_ov042_02258aa0[1] = {0x1019};

Unk_ov042_Entry data_ov042_02258ae8[3] = {
    {2, data_ov004_0224f2d4, 0, data_ov004_0224f2d8},
    {1, 1, 0, data_ov042_02258abc},
    {0, 2, 0, data_ov042_02258b00},
};

Unk_ov042_Scene data_ov042_02258ad0 = {&data_ov042_02258aac, 0, &data_ov042_02258aa4, &data_ov042_02258ab4, 0x32, -1};

Unk_ov042_Grid data_ov042_02258aa4 = {data_ov042_02258aa0, 1, 1};

Unk_ov042_Rec data_ov042_02258abc[1] = {
    {0x1000009, 0x1ae0002, 0x80000000, 0, 0x800000},
};

Unk_020b4f8c data_ov042_02258b58[2] = {
    Unk_020b4f8c(0x1d, Unk_020b4f8c_Vec(0x10000, 0x200, 0x9000), 0x11000000, 0, 2, 2, -0x8000, 2),
    Unk_020b4f8c(0x3c, Unk_020b4f8c_Vec(0, 0, 0), 0, 0, 2, 2, 0, 0),
};

Unk_ov042_Head data_ov042_02258aac = {3, data_ov042_02258ae8};
