// mwcc-version: 1.2/base
#include "types.h"

// ov021: map scene tables (a scene record, its entry list, the id grid, the static map objects).
// Generated by pipeline_wip/smallov2_work/gen.py from the original image; the definition order below
// reproduces the original data/bss order (mwcc size heapsort) and the __sinit order.

// 12-byte vector with a copy constructor (so it is passed by address of a copy)
struct Unk_020b4f8c_Vec {
    s32 x, y, z;
    Unk_020b4f8c_Vec(s32 a, s32 b, s32 c) {
        x = a;
        y = b;
        z = c;
    }
    Unk_020b4f8c_Vec(const Unk_020b4f8c_Vec &o) {
        x = o.x;
        y = o.y;
        z = o.z;
    }
};

// vector object with an out-of-line (main) destructor 0x02000c8c
struct Unk_02000c8c : Unk_020b4f8c_Vec {
    Unk_02000c8c(s32 a, s32 b, s32 c) : Unk_020b4f8c_Vec(a, b, c) {}
    ~Unk_02000c8c();
};

// 0x1c-byte map object: constructor 0x020b4f8c, destructor 0x020b4fc0 (both in main)
struct Unk_020b4f8c {
    u8 pad[0x1c];
    Unk_020b4f8c(u8 id, Unk_020b4f8c_Vec v, u32 w, s16 s, u8 p, u8 q, s16 r, u8 t);
    ~Unk_020b4f8c();
};

struct Unk_ov021_Entry {  // one list of the scene: kind 2 = ids (u32), 1 and 0 = 20-byte records
    u8 kind;
    u8 count;
    u16 pad;
    void *list;
};

struct Unk_ov021_Head {
    u32 count;
    Unk_ov021_Entry *entries;
};

struct Unk_ov021_Grid {  // width x height ids
    u32 *ids;
    u8 width;
    u8 height;
    u16 pad;
};

struct Unk_ov021_Objs {
    Unk_020b4f8c *objs;
    u32 count;
};

struct Unk_ov021_Rec {
    u32 w[5];
};

struct Unk_ov021_Scene {  // 24 bytes; main's table data_020e4280 points to it
    Unk_ov021_Head *head;
    s32 unk_04;
    Unk_ov021_Grid *grid;
    Unk_ov021_Objs *objs;
    s32 unk_10;
    s32 unk_14;
};

extern u8 data_ov004_0224f2d4;  // copied into the entry table by __sinit
extern u32 data_ov004_0224f2d8[];

// Declarations for data defined further down (definition order sets the data layout)
extern Unk_ov021_Objs data_ov021_02258c0c;
extern u32 data_ov021_02258c00[1];
extern Unk_ov021_Rec data_ov021_02258c24[1];
extern Unk_ov021_Entry data_ov021_02258c64[4];
extern Unk_ov021_Head data_ov021_02258c04;
extern Unk_ov021_Scene data_ov021_02258c4c;
extern u32 data_ov021_02258c14[2];
extern Unk_02000c8c data_ov021_02258cc4;
extern Unk_020b4f8c data_ov021_02258d0c[7];
extern Unk_ov021_Rec data_ov021_02258c38[1];
extern Unk_ov021_Grid data_ov021_02258c1c;

Unk_ov021_Objs data_ov021_02258c0c = {data_ov021_02258d0c, 7};

u32 data_ov021_02258c00[1] = {0x101d};

Unk_ov021_Rec data_ov021_02258c24[1] = {
    {0x1000009, 0x1a00002, 0x80000000, 0, 0x800000},
};

Unk_ov021_Entry data_ov021_02258c64[4] = {
    {2, data_ov004_0224f2d4, 0, data_ov004_0224f2d8},
    {2, 2, 0, data_ov021_02258c14},
    {1, 1, 0, data_ov021_02258c24},
    {0, 1, 0, data_ov021_02258c38},
};

Unk_ov021_Head data_ov021_02258c04 = {4, data_ov021_02258c64};

Unk_ov021_Scene data_ov021_02258c4c = {&data_ov021_02258c04, 0, &data_ov021_02258c1c, &data_ov021_02258c0c, 0x2f, -1};

u32 data_ov021_02258c14[2] = {0x100c2, 0x51};

Unk_02000c8c data_ov021_02258cc4(0x10000, 0x200, 0x1d000);

Unk_020b4f8c data_ov021_02258d0c[7] = {
    Unk_020b4f8c(0x3c, Unk_020b4f8c_Vec(0, 0, 0), 0x800000, 0, 2, 2, 0, 4),
    Unk_020b4f8c(0x21, Unk_020b4f8c_Vec(0x1b000, 0, 0x1a000), 0x23800000, -0x4000, 2, 2, -0x4000, 2),
    Unk_020b4f8c(0x29, Unk_020b4f8c_Vec(0x1b000, 0, 0x1e000), 0x23800000, -0x4000, 2, 2, -0x4000, 3),
    Unk_020b4f8c(0x22, data_ov021_02258cc4, 0x23800000, -0x8000, 2, 2, -0x8000, 1),
    Unk_020b4f8c(0x27, Unk_020b4f8c_Vec(0x16000, 0, 0x1d000), 0x23800000, -0x8000, 2, 2, -0x8000, 3),
    Unk_020b4f8c(0x25, Unk_020b4f8c_Vec(0x5000, 0, 0x1a000), 0x23800000, 0x4000, 2, 2, 0x4000, 3),
    Unk_020b4f8c(0x23, Unk_020b4f8c_Vec(0x5000, 0, 0x1a000), 0x23800000, 0x4000, 2, 2, 0x4000, 3),
};

Unk_ov021_Rec data_ov021_02258c38[1] = {
    {0xf0006e, 0x1500000, 0, 0, 0xd00c},
};

Unk_ov021_Grid data_ov021_02258c1c = {data_ov021_02258c00, 1, 1};
