// mwcc-version: 1.2/base
#include "types.h"

// ov038: map scene tables (a scene record, its entry list, the id grid, the static map objects).
// Generated by pipeline_wip/smallov2_work/gen.py from the original image; the definition order below
// reproduces the original data/bss order (mwcc size heapsort) and the __sinit order.

// 12-byte vector with a copy constructor (so it is passed by address of a copy)
struct Unk_020b4f8c_Vec {
    s32 x, y, z;
    Unk_020b4f8c_Vec(s32 a, s32 b, s32 c) {
        x = a;
        y = b;
        z = c;
    }
    Unk_020b4f8c_Vec(const Unk_020b4f8c_Vec &o) {
        x = o.x;
        y = o.y;
        z = o.z;
    }
};

// 0x1c-byte map object: constructor 0x020b4f8c, destructor 0x020b4fc0 (both in main)
struct Unk_020b4f8c {
    u8 pad[0x1c];
    Unk_020b4f8c(u8 id, Unk_020b4f8c_Vec v, u32 w, s16 s, u8 p, u8 q, s16 r, u8 t);
    ~Unk_020b4f8c();
};

struct Unk_ov038_Entry {  // one list of the scene: kind 2 = ids (u32), 1 and 0 = 20-byte records
    u8 kind;
    u8 count;
    u16 pad;
    void *list;
};

struct Unk_ov038_Head {
    u32 count;
    Unk_ov038_Entry *entries;
};

struct Unk_ov038_Grid {  // width x height ids
    u32 *ids;
    u8 width;
    u8 height;
    u16 pad;
};

struct Unk_ov038_Objs {
    Unk_020b4f8c *objs;
    u32 count;
};

struct Unk_ov038_Rec {
    u32 w[5];
};

struct Unk_ov038_Scene {  // 24 bytes; main's table data_020e4280 points to it
    Unk_ov038_Head *head;
    s32 unk_04;
    Unk_ov038_Grid *grid;
    Unk_ov038_Objs *objs;
    s32 unk_10;
    s32 unk_14;
};

extern u8 data_ov004_0224f2d4;  // copied into the entry table by __sinit
extern u32 data_ov004_0224f2d8[];

// Declarations for data defined further down (definition order sets the data layout)
extern u32 data_ov038_02258a40[1];
extern Unk_ov038_Grid data_ov038_02258a44;
extern Unk_ov038_Head data_ov038_02258a4c;
extern Unk_ov038_Entry data_ov038_02258a70[3];
extern Unk_020b4f8c data_ov038_02258aec[1];
extern Unk_ov038_Rec data_ov038_02258aa0[2];
extern Unk_ov038_Rec data_ov038_02258a5c[1];
extern Unk_ov038_Scene data_ov038_02258a88;
extern Unk_ov038_Objs data_ov038_02258a54;

u32 data_ov038_02258a40[1] = {0x1015};

Unk_ov038_Grid data_ov038_02258a44 = {data_ov038_02258a40, 1, 1};

Unk_ov038_Head data_ov038_02258a4c = {3, data_ov038_02258a70};

Unk_ov038_Entry data_ov038_02258a70[3] = {
    {2, data_ov004_0224f2d4, 0, data_ov004_0224f2d8},
    {1, 1, 0, data_ov038_02258a5c},
    {0, 2, 0, data_ov038_02258aa0},
};

Unk_020b4f8c data_ov038_02258aec[1] = {
    Unk_020b4f8c(0x3c, Unk_020b4f8c_Vec(0, 0, 0), 0, 0, 2, 2, 0, 4),
};

Unk_ov038_Rec data_ov038_02258aa0[2] = {
    {0xf00076, 0x1a00000, 0, 0, 0xd019},
    {0xb0002c, 0x1b00000, 0x40000000, 0, 0},
};

Unk_ov038_Rec data_ov038_02258a5c[1] = {
    {0x1000009, 0x1c00002, 0x80000000, 0, 0x800000},
};

Unk_ov038_Scene data_ov038_02258a88 = {&data_ov038_02258a4c, 0, &data_ov038_02258a44, &data_ov038_02258a54, 0x32, -1};

Unk_ov038_Objs data_ov038_02258a54 = {data_ov038_02258aec, 1};
