#ifndef TALK_VILLAGERTALKTOPICS_H
#define TALK_VILLAGERTALKTOPICS_H

#include "types.h"
#include "talk/VillagerTalkRequestReplyTopics.h"

// Villager talk topic state functions: the remaining topic state functions (greetings, memories, errands, items, ...). Views of the VillagerTalk object; base of the next topic class (ov069 chain).
// Members defined in src/main/unk_0201c050.cpp. The member-pointer fields are typed with VillagerTalkRequestItemTopics; that unit casts them to its per-class types.
struct TalkTopic;
struct TalkTopicMsg;
struct FishSpawnRow;
struct ClockDateTime;
struct VillagerStateView;

class VillagerTalkTopics : public VillagerTalkRequestReplyTopics {
public:
    void selectEtcPush(TalkTopicMsg *out);
    void endEtcPushHit();
    void selectEtcHit(TalkTopicMsg *out);
    void endAiFall();
    void selectAiFall(TalkTopicMsg *out);
    void selectEvBirthMsg4(TalkTopicMsg *out);
    void selectEvBirthMsg3(TalkTopicMsg *out);
    void openEvBirthChoice();
    void selectEvBirthMsg2(TalkTopicMsg *out);
    void continueEvBirthMsg7();
    void selectEvBirthMsg7(TalkTopicMsg *out);
    void continueEvBirthMsg6();
    void selectEvBirthMsg6(TalkTopicMsg *out);
    void selectEvBirthMsg5(TalkTopicMsg *out);
    void giveEvBirthPresent();
    void continueEvBirthFriends();
    void selectEvBirthMsg1(TalkTopicMsg *out);
    void stopBirthdayBgm();
    void playBirthdayBgm();
    void updateEvBirthTurn();
    void openEvKaraokeChoice();
    void selectEvKaraokeMsg3(TalkTopicMsg *out);
    void selectEvKaraokeTalk(TalkTopicMsg *out);
    s32 selectSituationGreeting(TalkTopicMsg *out);
    void selectTsuAlwaysEntry(TalkTopicMsg *out);
    void selectTsuMove2(TalkTopicMsg *out);
    void selectTsuMove1Part1(TalkTopicMsg *out);
    void selectTsuMove1B(TalkTopicMsg *out);
    void openTsuMove1Choice();
    void selectTsuMove1(TalkTopicMsg *out);
    void openEtcConnectChoice();
    void continueGreetingB();
    void startGreetingB();
    void selectTsuTopic(TalkTopicMsg *out);
    void setTsuTextVariables();
    s32 pickTsuTopicIndex(u8 *a, s32 b);
    BOOL selectEvFmarket1();
    BOOL selectEvArbeit();
    BOOL selectTsuStar();
    u32 selectTsuDrama();
    BOOL selectTsuEvent();
    u32 findTsuEvent2Message(u8 *a, s32 *b, u8 *c, u32 *d);
    u32 findTsuEvent1Message(u8 *a, s32 *b, u8 *c, u32 *d);
    BOOL selectTsuMemory();
    BOOL selectTsuAlways();
    BOOL selectTsuDress();
    BOOL selectTsuGhint();
    BOOL selectTsuHobbyAct();
    BOOL selectTsuNoAct();
    BOOL selectTsuSeAct();
    BOOL selectTsuFlAct();
    BOOL selectTsuFuAct();
    BOOL selectTsuClAct();
    BOOL selectTsuFoAct();
    BOOL selectTsuFiAct();
    BOOL selectTsuInAct();
    void selectTsuActMessage(s32 r1, TalkTopic *d);
    BOOL selectTsuHobbyHint();
    BOOL selectTsuNoHint();
    BOOL selectTsuSeHint();
    BOOL selectTsuFlHint();
    BOOL selectTsuFuHint();
    BOOL selectTsuClHint();
    BOOL selectTsuFoHint();
    s32 selectTsuFiHint();
    void setFishTimeSlot(s32 a, u16 *p, s32 c, FishSpawnRow **arr, s32 last);
    s32 selectTsuInHint();
    void selectEtcCancel(TalkTopicMsg *out);
    void selectQ10Leave(TalkTopicMsg *out);
    void selectQ10Con(TalkTopicMsg *out);
    void storeReservation();
    void selectQ10Reserved(TalkTopicMsg *out);
    void selectQError3(TalkTopicMsg *out);
    void selectQError2(TalkTopicMsg *out);
    void selectQError1(TalkTopicMsg *out);
    void checkReserveTime();
    void openReserveTimeEntry();
    void selectQ10Reserve(TalkTopicMsg *out);
    void openQ10ReqChoice();
    void selectQ10Req(TalkTopicMsg *out);
    void selectQ12FullPart2(TalkTopicMsg *out);
    void recheckPocketsForQItem();
    void selectQ12FullPart1(TalkTopicMsg *out);
    void onQ12FullClose();
    void selectQ12Full(TalkTopicMsg *out);
    void onQ12EndClose();
    void selectQ12End(TalkTopicMsg *out);
    void gotoQ12End();
    void putQItemInPocket();
    void selectQItem(TalkTopicMsg *out);
    void checkPocketsForQItem();
    void selectQ12Thanks(TalkTopicMsg *out);
    void selectQ12Report(TalkTopicMsg *out);
    void selectQ12Other(TalkTopicMsg *out);
    void selectEvArbeitEnd(TalkTopicMsg *out);
    void gotoEvArbeitEnd();
    void giveArbeitReward();
    void selectEvArbeitReceive(TalkTopicMsg *out);
    void onArbeitItemPicked();
    void selectQPreitemB(TalkTopicMsg *out);
    void gotoQRewardTopic();
    void takeRequestItem();
    void selectQThanks(TalkTopicMsg *out);
    void selectQMissB(TalkTopicMsg *out);
    void giveBackHeldItem();
    void selectQMiss(TalkTopicMsg *out);
    void checkRequestItem();
    void onRequestItemPicked();
    void openRequestItemPicker();
    void advanceRequestStep();
    void selectQRevenge(TalkTopicMsg *out);
    void handOverRequestReward();
    void gotoQEndOrRevenge();
    void selectQPay(TalkTopicMsg *out);
    void gotoQPay();
    void keepItemThenGotoQPay();
    void selectQNlose(TalkTopicMsg *out);
    void selectQNwin(TalkTopicMsg *out);
    void gotoQNlose();
    void onNloseCatchPicked();
    void checkVillagerCatch();
    void selectQPdraw(TalkTopicMsg *out);
    void cancelRequestChain();
    void selectQPlose(TalkTopicMsg *out);
    void selectQPwin2(TalkTopicMsg *out);
    void gotoQPwin2();
    void takePlayerCatch();
    void selectQPwin(TalkTopicMsg *out);
    void compareCatchPrice();
    void onCatchPicked();
    void openCatchPicker();
    void selectQ05Talk(TalkTopicMsg *out);
    void selectCollectRequest(TalkTopicMsg *out);
    void selectDeliveryEnd(TalkTopicMsg *out);
    void gotoDeliveryEnd();
    void giveRewardItem();
    void selectQItemC(TalkTopicMsg *out);
    void gotoRewardItem();
    void selectQPreitem(TalkTopicMsg *out);
    void gotoRewardOrEnd();
    void selectQ06Bad(TalkTopicMsg *out);
    void selectQ06Normal(TalkTopicMsg *out);
    void selectQ06Good(TalkTopicMsg *out);
    void onPresentOpinionChoice(s32 unused, s32 idx);
    void continueDeliveryReport(void *p);
    void selectDeliveryReport(TalkTopicMsg *out);
    void selectDeliveryReminder(TalkTopicMsg *out);
    void selectDeliveryFin(TalkTopicMsg *out);
    void showLetter();
    void closeLetter();
    void selectQ07Show(TalkTopicMsg *out);
    void continueLetterRead();
    void gotoDeliveryFin();
    void selectQ07Read(TalkTopicMsg *out);
    void finishOpenedLetter();
    void selectQ07Open2(TalkTopicMsg *out);
    void continuePresentAccepted();
    void selectQ06Open2(TalkTopicMsg *out);
    void keepDislikedPresent();
    void selectQ06Open3(TalkTopicMsg *out);
    void continuePresentLiked();
    void selectQ06Open1(TalkTopicMsg *out);
    void judgePresent();
    void continueDeliveryReceived();
    void selectDeliveryReceived(TalkTopicMsg *out);
    void onDeliveryItemPicked();
    void reopenWindow();
    void selectQIcancel(TalkTopicMsg *out);
    void openDeliveryItemPicker();
    void selectQTimeover(TalkTopicMsg *out);
    void finishOpenedDelivery();
    void selectDeliveryOpened(TalkTopicMsg *out);
    void finishLostDelivery();
    void selectDeliveryLost(TalkTopicMsg *out);
    void finishLateDelivery();
    void selectDeliveryLateReply(TalkTopicMsg *out);
    void continueDeliveryLate();
    void continueLateLetterShown();
    BOOL tryOfferVisitRequest(void *a, void *b);
    BOOL tryOfferCollectRequest(void *a);
    BOOL tryOfferDeliveryRequest(void *a, void *b);
    s32 pickRandomOtherVillager();
    s32 tryAddActiveRequestChoice(void *a, void *b);
    BOOL tryAddVisitReminderChoice(void *a, void *b, u32 c);
    void setVisitTimeArgs(ClockDateTime *p);
    BOOL tryAddCollectRequestChoice(void *a, void *b, u32 c);
    s32 openFossilRequestMenu();
    s32 openShirtRequestMenu();
    s32 openFurnitureRequestMenu();
    s32 openCreatureRequestMenu(BOOL (*f)(u16 *), s32 pa, s32 pb);
    BOOL tryAddDeliveryClientChoice(s32 unused, s32 a, s32 b);
    BOOL tryAddDeliveryRecipientChoice(s32 a, s32 b);
    BOOL tryAddHandOverChoice(s32 a, s32 b);
    void selectEtcConnect(TalkTopicMsg *out);
    void selectApNicknRefused(TalkTopicMsg *out);
    void selectApNicknAccepted(TalkTopicMsg *out);
    void retryNicknameInput();
    void openNicknameConfirmChoice();
    void selectApNicknConfirm(TalkTopicMsg *out);
    void onNicknameEntered();
    void openNicknameKeyboard(s32 unused);
    void selectApNicknDisliked(TalkTopicMsg *out);
    void openNicknameLikeChoice();
    void makeNickname();
    void selectApNicknProposal(TalkTopicMsg *out);
    void openNicknameAcceptChoice();
    void selectApHabitDeclined(TalkTopicMsg *out);
    void selectApHabitB(TalkTopicMsg *out);
    void openHabitConfirmChoice();
    void selectApHabitConfirm(TalkTopicMsg *out);
    void retryHabitInput();
    void onHabitEntered();
    void openHabitKeyboard(s32);
    void selectApHabitPart1(TalkTopicMsg *out);
    void openHabitAcceptChoice();
    void selectApTopic(TalkTopicMsg *out);
    BOOL selectApSell();
    BOOL selectApTrade();
    BOOL selectApBuy();
    BOOL selectApPresent2();
    BOOL selectApPresent1();
    BOOL selectApMail();
    BOOL selectApNickn();
    BOOL selectApItem();
    BOOL selectApHabit();
    void select3pTalk(TalkTopicMsg *out);
    void continueAfterGreeting();
    void ensureSpeakerMemory();
    void setGreetingArgs();
    void setFashionArg(u32 a, void *b);
    void setStringTableArg(u32 a, u32 b);
    void selectGreeting(TalkTopicMsg *out);
    BOOL isMoodTired(s32 x);
    BOOL isMoodSad(s32 x);
    BOOL isMoodAngry(s32 x);
    TalkTopic *getBeeStingTopic(u32 *out, VillagerStateView *rec);
    BOOL isPlayerStung(VillagerStateView *rec);
    BOOL hasFleas();
    TalkTopic *getPoisonTopic(s32 x);
    BOOL findDangerousInsect(volatile s32 *out, void *p);
    TalkTopic *getForeignTopic();
    BOOL isForeignMemory(s32 x);
    TalkTopic *getFirstMeetingTopic(u32 *out, void *scene);
    BOOL isFirstMeeting(s32 x);
    BOOL isBeeSwarmOut();
    BOOL hasFallen();
    s32 getGreetingStatus(s32 *out);
};

#endif
