// mwcc-flags: -nothumb -O4,p
// RC_020f0fb4: autoload_2 0x020f0fb4-0x020f30fc (154 functions) + .data 0x0213b2c4-0x0213b914 (data_0213b2c4 + 31 vtables).
// mwcc 1.2/base, C++, ARM, -O4,p. REAL-CLASS shape (pipeline_wip/realclass_work/PLAN.md): the scene/task class family, the whole source
// file (G007a + the first part of G008a). Generated by pipeline_wip/realclass2_work/scene/gen.py from the matched PARTIAL sources.
// Classes (named after the dsd vtable label, vtable object = label - 8):
//   Unk_0213b8e8              base: C2 f3078 (C1 unreferenced, dead-stripped), ~ D2 f2fc8 / D0 f3000 / D1 f3040, virtuals vfunc_08..28,
//                             resource helpers f2aec..f2cd4, f2eac. vfunc_24 (slot 9) is DEFINED IN MAIN: the empty Thumb function
//                             func_02003f78 of src/main/unk_020039ec.cpp (aliases.txt gives it the name _ZN12Unk_0213b8e88vfunc_24Ei).
//   Unk_0213b8b4 : base       mid-level base: C1 f2a3c / C2 f2a94 (both kept: C1 is called from outside, C2 by the derived ctors),
//                             ~ D2 f29c8 / D0 f29ec / D1 f2a18, overrides vfunc_0c f2968, vfunc_1c f2938, vfunc_20 f2910, vfunc_24 f28c0
//   26 + 3 subclasses         per class: ctor (C1; C2 unreferenced), ~ (D0, D1; D2 unreferenced except for the two bases), vfunc_0c
//                             (the scene's INIT) and a few overrides (0x0213b338: sub-object at +8, vfunc_10/1c/20/28; 0x0213b610:
//                             sub-object at +8, vfunc_10/28; 0x0213b7e4: vfunc_14). The sub-objects at +8 are objects of the BGM
//                             animation file (G011, still PARTIAL): raw storage here, constructed/destroyed by explicit calls of their
//                             extern "C" functions (f833c/f831c, f80d8/f80ac), which is the same code as a member object.
// Class DECLARATION order (base, mid, then 0x0213b2d0, 574, 338, 36c, ..., 880; see realclass2_work/inv.py) sets the vtable order: mwcc
// creates the vtables last, in reverse declaration order, and heapsorts the file's data by size. Keep it.
// Every function lands on its original address with the original bytes; every old func_ name stays (aliases.txt), nothing is renamed
// except the vtables (renames.txt, _ZTV at the real start).
#include "types.h"

struct Bytes4 {
    u8 b0, b1, b2, b3;
};

struct Player {
    /* 0x00 */ u8 pad0[0x15];
    /* 0x15 */ Bytes4 unk_15;
};

struct F30 {
    u8 pad[0x3c];
    u8 f3c;
};

class Unk_0213b8e8;

// sound manager data_021f5b80 (SndMgr, unk_020f0dec.cpp)
struct Glob {
    /* 0x00 */ u8 pad0[0x28];
    /* 0x28 */ void *f28;
    /* 0x2c */ Unk_0213b8e8 *f2c;
    /* 0x30 */ F30 *f30;
    /* 0x34 */ u8 pad1[0x19];
    /* 0x4d */ u8 f4d;
    /* 0x4e */ u8 pad2[0x14];
    /* 0x62 */ u8 f62;
    /* 0x63 */ u8 pad3[0x10];
    /* 0x73 */ u8 f73;
};

// BGM animation object (sub-object at +8 of two scene classes; functions in the G011 file, still PARTIAL)
class SubObj {
public:
    virtual void vfunc_00();
};

extern "C" {
extern Glob data_021f5b80;
extern Player data_021f59f4;

void _ZdlPv(void *p);
void *func_020edc88(void);
void *func_020ed960(void);
void *func_020ed978(u32 a);
BOOL func_020edd58(Player *o, u32 a, u32 b, Bytes4 s);
void func_020edd20(Player *p, s32 v);
void func_0210be44(void *p);
void func_0210bd58(void *a, u32 b);
void *func_0210bd4c(void *a);
void func_0210cc14(s32 a, void *b);
void func_0210a388(s32 a, void *b, u32 c);
void func_0210a460(s32 a, s32 b);
void func_0210a310(s32 a, s32 b);
void func_020efab8(void);
void func_020efa64(Glob *g);
void func_020efc84(Glob *g, s32 a, s32 b);
void func_020f0838(Glob *g, s32 v);
void func_020f0980(Glob *g);
void func_020f0dec(Glob *g);
void func_020f0df8(Glob *g);
void func_020f443c(void);
void func_020f4468(void);
void func_020f44f0(s32 v);
void func_020f5070(F30 *a, s32 b);
void func_020f51b4(F30 *v);
void func_020f80a4(void *p, s32 v);
void func_020f80ac(void *p);
void func_020f80d8(void *p);
void func_020f8290(void *p, s32 v);
void func_020f831c(void *p);
void func_020f833c(void *p);
}

// colour passed by value to func_020edd58 (byte 0 is replaced by the caller's argument)
extern "C" Bytes4 data_0213b2c4 = {0x00, 0x02, 0xff, 0x00};

// vtable 0x0213b8e0 (dsd label data_0213b8e8)
class Unk_0213b8e8 {
public:
    Unk_0213b8e8();                     // C2 0x020f3078 (C1 unreferenced, dead-stripped)
    virtual ~Unk_0213b8e8();            // D2 0x020f2fc8, D0 0x020f3000, D1 0x020f3040
    virtual void vfunc_08();            // 0x020f2fc4
    virtual void vfunc_0c();            // 0x020f2fc0
    virtual void vfunc_10();            // 0x020f2fac
    virtual void vfunc_14();            // 0x020f2f6c
    virtual void vfunc_18();            // 0x020f2e58
    virtual void vfunc_1c(s32 a);       // 0x020f2dec
    virtual void vfunc_20();            // 0x020f2dcc
    virtual void vfunc_24(s32 a);       // main func_02003f78 (empty Thumb function, defined in main)
    virtual void vfunc_28(u32 a, u32 c); // 0x020f2dc8
    void setTracks(s32 v);              // 0x020f2eac
    void setup(u32 a, s32 b);           // 0x020f2cd4
    void allocRes4();                   // 0x020f2ca8
    void allocRes11(s32 n);             // 0x020f2c58
    void allocRes5();                   // 0x020f2c2c
    void allocRes6();                   // 0x020f2be4
    void allocRes17();                  // 0x020f2b9c
    void allocRes18();                  // 0x020f2b60
    void allocRes13();                  // 0x020f2b34
    void allocRes12();                  // 0x020f2aec

    /* 0x04 */ s8 id;
    /* 0x05 */ u8 f5;
    /* 0x06 */ u8 f6;
};

// vtable 0x0213b8ac (dsd label data_0213b8b4)
class Unk_0213b8b4 : public Unk_0213b8e8 {
public:
    Unk_0213b8b4();                     // C1 0x020f2a3c, C2 0x020f2a94
    virtual ~Unk_0213b8b4();            // D2 0x020f29c8, D0 0x020f29ec, D1 0x020f2a18
    virtual void vfunc_0c();            // 0x020f2968
    virtual void vfunc_1c(s32 a);       // 0x020f2938
    virtual void vfunc_20();            // 0x020f2910
    virtual void vfunc_24(s32 a);       // 0x020f28c0
};

// vtable 0x0213b2c8 (dsd label data_0213b2d0)
class Unk_0213b2d0 : public Unk_0213b8b4 {
public:
    Unk_0213b2d0();                     // C1 0x020f2878 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b2d0();            // D0 0x020f2828, D1 0x020f2854
    virtual void vfunc_0c();            // 0x020f27d0
};

// vtable 0x0213b56c (dsd label data_0213b574)
class Unk_0213b574 : public Unk_0213b8b4 {
public:
    Unk_0213b574();                     // C1 0x020f2788 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b574();            // D0 0x020f2738, D1 0x020f2764
    virtual void vfunc_0c();            // 0x020f26d8
};

// vtable 0x0213b330 (dsd label data_0213b338)
class Unk_0213b338 : public Unk_0213b8e8 {
public:
    Unk_0213b338();                     // C1 0x020f269c (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b338();            // D0 0x020f2634, D1 0x020f266c
    virtual void vfunc_0c();            // 0x020f2568
    virtual void vfunc_10();            // 0x020f2544
    virtual void vfunc_1c(s32 a);       // 0x020f24fc
    virtual void vfunc_20();            // 0x020f24c0
    virtual void vfunc_28(u32 a, u32 c); // 0x020f2534

    /* 0x08 */ u32 sub[5];          // BGM animation object (G011 file; has a vptr, so word-aligned)
    /* 0x1c */ u8 state;
    /* 0x1d */ u8 f1d;
};

// vtable 0x0213b364 (dsd label data_0213b36c)
class Unk_0213b36c : public Unk_0213b8e8 {
public:
    Unk_0213b36c();                     // C1 0x020f2494 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b36c();            // D0 0x020f2444, D1 0x020f2470
    virtual void vfunc_0c();            // 0x020f23fc
};

// vtable 0x0213b398 (dsd label data_0213b3a0)
class Unk_0213b3a0 : public Unk_0213b8e8 {
public:
    Unk_0213b3a0();                     // C1 0x020f23d0 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b3a0();            // D0 0x020f2380, D1 0x020f23ac
    virtual void vfunc_0c();            // 0x020f2338
};

// vtable 0x0213b3cc (dsd label data_0213b3d4)
class Unk_0213b3d4 : public Unk_0213b8e8 {
public:
    Unk_0213b3d4();                     // C1 0x020f230c (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b3d4();            // D0 0x020f22bc, D1 0x020f22e8
    virtual void vfunc_0c();            // 0x020f2274
};

// vtable 0x0213b400 (dsd label data_0213b408)
class Unk_0213b408 : public Unk_0213b8e8 {
public:
    Unk_0213b408();                     // C1 0x020f2248 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b408();            // D0 0x020f21f8, D1 0x020f2224
    virtual void vfunc_0c();            // 0x020f21b0
};

// vtable 0x0213b434 (dsd label data_0213b43c)
class Unk_0213b43c : public Unk_0213b8e8 {
public:
    Unk_0213b43c();                     // C1 0x020f2184 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b43c();            // D0 0x020f2134, D1 0x020f2160
    virtual void vfunc_0c();            // 0x020f20dc
};

// vtable 0x0213b468 (dsd label data_0213b470)
class Unk_0213b470 : public Unk_0213b8e8 {
public:
    Unk_0213b470();                     // C1 0x020f20b0 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b470();            // D0 0x020f2060, D1 0x020f208c
    virtual void vfunc_0c();            // 0x020f2018
};

// vtable 0x0213b49c (dsd label data_0213b4a4)
class Unk_0213b4a4 : public Unk_0213b8e8 {
public:
    Unk_0213b4a4();                     // C1 0x020f1fec (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b4a4();            // D0 0x020f1f9c, D1 0x020f1fc8
    virtual void vfunc_0c();            // 0x020f1f44
};

// vtable 0x0213b4d0 (dsd label data_0213b4d8)
class Unk_0213b4d8 : public Unk_0213b8e8 {
public:
    Unk_0213b4d8();                     // C1 0x020f1f18 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b4d8();            // D0 0x020f1ec8, D1 0x020f1ef4
    virtual void vfunc_0c();            // 0x020f1e70
};

// vtable 0x0213b504 (dsd label data_0213b50c)
class Unk_0213b50c : public Unk_0213b8e8 {
public:
    Unk_0213b50c();                     // C1 0x020f1e44 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b50c();            // D0 0x020f1df4, D1 0x020f1e20
    virtual void vfunc_0c();            // 0x020f1d9c
};

// vtable 0x0213b538 (dsd label data_0213b540)
class Unk_0213b540 : public Unk_0213b8e8 {
public:
    Unk_0213b540();                     // C1 0x020f1d70 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b540();            // D0 0x020f1d20, D1 0x020f1d4c
    virtual void vfunc_0c();            // 0x020f1cc8
};

// vtable 0x0213b2fc (dsd label data_0213b304)
class Unk_0213b304 : public Unk_0213b8e8 {
public:
    Unk_0213b304();                     // C1 0x020f1c9c (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b304();            // D0 0x020f1c4c, D1 0x020f1c78
    virtual void vfunc_0c();            // 0x020f1bf4
};

// vtable 0x0213b5a0 (dsd label data_0213b5a8)
class Unk_0213b5a8 : public Unk_0213b8e8 {
public:
    Unk_0213b5a8();                     // C1 0x020f1bc8 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b5a8();            // D0 0x020f1b78, D1 0x020f1ba4
    virtual void vfunc_0c();            // 0x020f1b30
};

// vtable 0x0213b5d4 (dsd label data_0213b5dc)
class Unk_0213b5dc : public Unk_0213b8e8 {
public:
    Unk_0213b5dc();                     // C1 0x020f1b04 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b5dc();            // D0 0x020f1ab4, D1 0x020f1ae0
    virtual void vfunc_0c();            // 0x020f1a6c
};

// vtable 0x0213b608 (dsd label data_0213b610)
class Unk_0213b610 : public Unk_0213b8e8 {
public:
    Unk_0213b610();                     // C1 0x020f1a38 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b610();            // D0 0x020f19d0, D1 0x020f1a08
    virtual void vfunc_0c();            // 0x020f1988
    virtual void vfunc_10();            // 0x020f1964
    virtual void vfunc_28(u32 a, u32 c); // 0x020f191c

    /* 0x08 */ u32 sub[5];          // BGM animation object (G011 file; has a vptr, so word-aligned)
};

// vtable 0x0213b63c (dsd label data_0213b644)
class Unk_0213b644 : public Unk_0213b8e8 {
public:
    Unk_0213b644();                     // C1 0x020f18f0 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b644();            // D0 0x020f18a0, D1 0x020f18cc
    virtual void vfunc_0c();            // 0x020f1858
};

// vtable 0x0213b670 (dsd label data_0213b678)
class Unk_0213b678 : public Unk_0213b8e8 {
public:
    Unk_0213b678();                     // C1 0x020f182c (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b678();            // D0 0x020f17dc, D1 0x020f1808
    virtual void vfunc_0c();            // 0x020f1794
};

// vtable 0x0213b6a4 (dsd label data_0213b6ac)
class Unk_0213b6ac : public Unk_0213b8e8 {
public:
    Unk_0213b6ac();                     // C1 0x020f1768 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b6ac();            // D0 0x020f1718, D1 0x020f1744
    virtual void vfunc_0c();            // 0x020f16d0
};

// vtable 0x0213b6d8 (dsd label data_0213b6e0)
class Unk_0213b6e0 : public Unk_0213b8e8 {
public:
    Unk_0213b6e0();                     // C1 0x020f16a4 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b6e0();            // D0 0x020f1654, D1 0x020f1680
    virtual void vfunc_0c();            // 0x020f160c
};

// vtable 0x0213b70c (dsd label data_0213b714)
class Unk_0213b714 : public Unk_0213b8e8 {
public:
    Unk_0213b714();                     // C1 0x020f15e0 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b714();            // D0 0x020f1590, D1 0x020f15bc
    virtual void vfunc_0c();            // 0x020f1548
};

// vtable 0x0213b740 (dsd label data_0213b748)
class Unk_0213b748 : public Unk_0213b8e8 {
public:
    Unk_0213b748();                     // C1 0x020f151c (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b748();            // D0 0x020f14cc, D1 0x020f14f8
    virtual void vfunc_0c();            // 0x020f1484
};

// vtable 0x0213b774 (dsd label data_0213b77c)
class Unk_0213b77c : public Unk_0213b8e8 {
public:
    Unk_0213b77c();                     // C1 0x020f1458 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b77c();            // D0 0x020f1408, D1 0x020f1434
    virtual void vfunc_0c();            // 0x020f13c0
};

// vtable 0x0213b7a8 (dsd label data_0213b7b0)
class Unk_0213b7b0 : public Unk_0213b8e8 {
public:
    Unk_0213b7b0();                     // C1 0x020f138c (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b7b0();            // D0 0x020f133c, D1 0x020f1368
    virtual void vfunc_0c();            // 0x020f12f4
};

// vtable 0x0213b7dc (dsd label data_0213b7e4)
class Unk_0213b7e4 : public Unk_0213b8e8 {
public:
    Unk_0213b7e4();                     // C1 0x020f12c8 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b7e4();            // D0 0x020f1278, D1 0x020f12a4
    virtual void vfunc_0c();            // 0x020f1238
    virtual void vfunc_14();            // 0x020f1200
};

// vtable 0x0213b810 (dsd label data_0213b818)
class Unk_0213b818 : public Unk_0213b8e8 {
public:
    Unk_0213b818();                     // C1 0x020f11d4 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b818();            // D0 0x020f1184, D1 0x020f11b0
    virtual void vfunc_0c();            // 0x020f1144
};

// vtable 0x0213b844 (dsd label data_0213b84c)
class Unk_0213b84c : public Unk_0213b8b4 {
public:
    Unk_0213b84c();                     // C1 0x020f1118 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b84c();            // D0 0x020f10c8, D1 0x020f10f4
    virtual void vfunc_0c();            // 0x020f1070
};

// vtable 0x0213b878 (dsd label data_0213b880)
class Unk_0213b880 : public Unk_0213b8e8 {
public:
    Unk_0213b880();                     // C1 0x020f1044 (C2 unreferenced, dead-stripped)
    virtual ~Unk_0213b880();            // D0 0x020f0ff4, D1 0x020f1020
    virtual void vfunc_0c();            // 0x020f0fb4
};

// Definitions in descending address order (mwcc emits a file's functions last to first).

Unk_0213b8e8::Unk_0213b8e8() {
    data_021f5b80.f2c = this;
    data_021f5b80.f4d = 0;
    data_021f5b80.f30->f3c = 0;
    if (data_021f5b80.f30 != 0) func_020f5070(data_021f5b80.f30, 210);
    func_020efc84(&data_021f5b80, 127, 127);
    func_0210a460(15, 100);
    id = -1;
    f5 = 0;
    f6 = 0;
    func_020f44f0(0);
}

Unk_0213b8e8::~Unk_0213b8e8() {
    data_021f5b80.f2c = 0;
    func_0210bd58(data_021f5b80.f28, 0);
}

void Unk_0213b8e8::vfunc_08() {
}

void Unk_0213b8e8::vfunc_0c() {
}

void Unk_0213b8e8::vfunc_10() {
    return func_020efa64(&data_021f5b80);
}

void Unk_0213b8e8::vfunc_14() {
    func_020f51b4(data_021f5b80.f30);
    data_021f5b80.f4d = 1;
    setTracks(15);
    f5 = 1;
}

void Unk_0213b8e8::setTracks(s32 v) {
    func_0210a310(11, v);
    func_0210a310(2, v);
    func_0210a310(4, v);
    func_0210a310(5, v);
    func_0210a310(6, v);
    func_0210a310(7, v);
    func_0210a310(8, v);
    func_0210a310(9, v);
    func_0210a310(10, v);
    func_0210a310(12, v);
    func_0210a310(15, v);
    func_0210a310(16, v);
    func_0210a310(17, v);
    func_0210a310(18, v);
    func_0210a310(19, v);
}

void Unk_0213b8e8::vfunc_18() {
    func_020f443c();
    void *t = func_020edc88();
    func_020edd20(&data_021f59f4, 1);
    if (data_021f5b80.f62 != 0) return;
    func_0210bd58(t, 1);
    func_020f0dec(&data_021f5b80);
}

void Unk_0213b8e8::vfunc_1c(s32 a) {
    s32 r;
    switch (a) {
    case 0:
    case 4:
        r = 133;
        break;
    case 1:
    case 3:
        r = 134;
        break;
    case 2:
        r = 135;
        break;
    }
    func_020f0980(&data_021f5b80);
    func_020f0838(&data_021f5b80, r);
    f6 = 1;
}

void Unk_0213b8e8::vfunc_20() {
    func_020ed978((u32)func_020ed960());
    f6 = 0;
}

void Unk_0213b8e8::vfunc_28(u32 a, u32 c) {
}

void Unk_0213b8e8::setup(u32 a, s32 b) {
    void *t = func_020edc88();
    if (data_021f5b80.f62 == 0) {
        func_020f0df8(&data_021f5b80);
        func_0210a388(0, t, a);
        func_0210be44(t);
    }
    Bytes4 q = data_0213b2c4;
    q.b0 = b;
    data_021f59f4.unk_15 = q;
    func_020edd58(&data_021f59f4, 0, 0, q);
    func_020f4468();
    func_0210be44(t);
}

void Unk_0213b8e8::allocRes4() {
    func_0210a388(4, func_020edc88(), 0x206c);
}

void Unk_0213b8e8::allocRes11(s32 n) {
    void *t = func_020edc88();
    for (s32 i = 0; i < n; i++) {
        func_0210a388(11, t, 0x650c);
    }
}

void Unk_0213b8e8::allocRes5() {
    func_0210a388(5, func_020edc88(), 0x31ac);
}

void Unk_0213b8e8::allocRes6() {
    void *t = func_020edc88();
    for (s32 i = 0; i < 2; i++) {
        func_0210a388(6, t, 0x7a4c);
    }
}

void Unk_0213b8e8::allocRes17() {
    void *t = func_020edc88();
    for (s32 i = 0; i < 4; i++) {
        func_0210a388(17, t, 0x356c);
    }
}

void Unk_0213b8e8::allocRes18() {
    void *t = func_020edc88();
    func_0210a388(18, t, 0x5ecc);
    func_0210a388(19, t, 0x46bc);
}

void Unk_0213b8e8::allocRes13() {
    func_0210a388(13, func_020edc88(), 0x1f4c);
}

void Unk_0213b8e8::allocRes12() {
    void *t = func_020edc88();
    for (s32 i = 0; i < 2; i++) {
        func_0210a388(12, t, 0x8cc);
    }
}

Unk_0213b8b4::Unk_0213b8b4() {
    if (data_021f5b80.f30 != 0) func_020f5070(data_021f5b80.f30, 209);
    id = 1;
    func_020f44f0(1);
    data_021f5b80.f73 = 0;
}

Unk_0213b8b4::~Unk_0213b8b4() {
}

void Unk_0213b8b4::vfunc_0c() {
    setup(0x21ef8, 1);
    allocRes11(3);
    allocRes13();
    allocRes12();
    func_0210be44(func_020edc88());
    func_020f0838(&data_021f5b80, 143);
    data_021f5b80.f62 = 0;
}

void Unk_0213b8b4::vfunc_1c(s32 a) {
    func_020ed978((u32)func_020ed960());
    Unk_0213b8e8::vfunc_1c(a);
}

void Unk_0213b8b4::vfunc_20() {
    Unk_0213b8e8::vfunc_20();
    func_020f0838(&data_021f5b80, 143);
}

void Unk_0213b8b4::vfunc_24(s32 a) {
    func_020ed978((u32)func_020ed960());
    if (a != 0) {
        if (a == 1) {
            func_020f0838(&data_021f5b80, 178);
        }
    } else {
        func_020f0838(&data_021f5b80, 143);
    }
}

Unk_0213b2d0::Unk_0213b2d0() {
    if (data_021f5b80.f30 != 0) func_020f5070(data_021f5b80.f30, 209);
    id = 2;
}

Unk_0213b2d0::~Unk_0213b2d0() {
}

void Unk_0213b2d0::vfunc_0c() {
    setup(0x1f340, 2);
    allocRes11(2);
    allocRes12();
    func_0210be44(func_020edc88());
    func_020f0838(&data_021f5b80, 143);
    data_021f5b80.f62 = 0;
}

Unk_0213b574::Unk_0213b574() {
    if (data_021f5b80.f30 != 0) func_020f5070(data_021f5b80.f30, 209);
    id = 3;
}

Unk_0213b574::~Unk_0213b574() {
}

void Unk_0213b574::vfunc_0c() {
    setup(0x21ef8, 3);
    allocRes11(2);
    allocRes13();
    allocRes12();
    func_0210be44(func_020edc88());
    func_020f0838(&data_021f5b80, 143);
    data_021f5b80.f62 = 0;
}

Unk_0213b338::Unk_0213b338() {
    func_020f833c(sub);
    id = 10;
    state = 0;
}

Unk_0213b338::~Unk_0213b338() {
    func_020f831c(sub);
}

void Unk_0213b338::vfunc_0c() {
    setup(0x10ea0, 5);
    allocRes4();
    allocRes5();
    allocRes6();
    allocRes17();
    allocRes18();
    void *t = func_020edc88();
    func_0210cc14(9, t);
    func_0210be44(t);
    f1d = (u8)(u32)func_0210bd4c(t);
    func_020f0838(&data_021f5b80, 144);
    allocRes12();
    func_0210be44(t);
    state = 1;
    data_021f5b80.f62 = 0;
    func_020f8290(sub, 1);
    func_0210a460(18, 63);
    func_0210a460(19, 63);
}

void Unk_0213b338::vfunc_10() {
    Unk_0213b8e8::vfunc_10();
    ((SubObj *)sub)->vfunc_00();
}

void Unk_0213b338::vfunc_28(u32 v, u32 c) {
    return func_020f8290(sub, v);
}

void Unk_0213b338::vfunc_1c(s32 a) {
    func_020ed978(f1d);
    Unk_0213b8e8::vfunc_1c(a);
    state = 2;
}

void Unk_0213b338::vfunc_20() {
    Unk_0213b8e8::vfunc_20();
    func_020f0838(&data_021f5b80, 144);
    allocRes12();
    func_0210be44(func_020edc88());
    state = 1;
}

Unk_0213b36c::Unk_0213b36c() {
    id = 19;
}

Unk_0213b36c::~Unk_0213b36c() {
}

void Unk_0213b36c::vfunc_0c() {
    setup(0x2a824, 6);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b3a0::Unk_0213b3a0() {
    id = 20;
}

Unk_0213b3a0::~Unk_0213b3a0() {
}

void Unk_0213b3a0::vfunc_0c() {
    setup(0x2a824, 7);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b3d4::Unk_0213b3d4() {
    id = 21;
}

Unk_0213b3d4::~Unk_0213b3d4() {
}

void Unk_0213b3d4::vfunc_0c() {
    setup(0x2a824, 8);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b408::Unk_0213b408() {
    id = 22;
}

Unk_0213b408::~Unk_0213b408() {
}

void Unk_0213b408::vfunc_0c() {
    setup(0x2a824, 9);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b43c::Unk_0213b43c() {
    id = 23;
}

Unk_0213b43c::~Unk_0213b43c() {
}

void Unk_0213b43c::vfunc_0c() {
    setup(0x2a824, 10);
    allocRes4();
    allocRes5();
    allocRes6();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b470::Unk_0213b470() {
    id = 24;
}

Unk_0213b470::~Unk_0213b470() {
}

void Unk_0213b470::vfunc_0c() {
    setup(0x2a824, 11);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b4a4::Unk_0213b4a4() {
    id = 30;
}

Unk_0213b4a4::~Unk_0213b4a4() {
}

void Unk_0213b4a4::vfunc_0c() {
    setup(0x232f4, 12);
    allocRes4();
    allocRes5();
    allocRes6();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b4d8::Unk_0213b4d8() {
    id = 31;
}

Unk_0213b4d8::~Unk_0213b4d8() {
}

void Unk_0213b4d8::vfunc_0c() {
    setup(0x232f4, 13);
    allocRes4();
    allocRes5();
    allocRes6();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b50c::Unk_0213b50c() {
    id = 32;
}

Unk_0213b50c::~Unk_0213b50c() {
}

void Unk_0213b50c::vfunc_0c() {
    setup(0x232f4, 14);
    allocRes4();
    allocRes5();
    allocRes6();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b540::Unk_0213b540() {
    id = 33;
}

Unk_0213b540::~Unk_0213b540() {
}

void Unk_0213b540::vfunc_0c() {
    setup(0x232f4, 15);
    allocRes4();
    allocRes5();
    allocRes6();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b304::Unk_0213b304() {
    id = 34;
}

Unk_0213b304::~Unk_0213b304() {
}

void Unk_0213b304::vfunc_0c() {
    setup(0x232f4, 16);
    allocRes4();
    allocRes5();
    allocRes6();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b5a8::Unk_0213b5a8() {
    id = 35;
}

Unk_0213b5a8::~Unk_0213b5a8() {
}

void Unk_0213b5a8::vfunc_0c() {
    setup(0x232f4, 17);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b5dc::Unk_0213b5dc() {
    id = 40;
}

Unk_0213b5dc::~Unk_0213b5dc() {
}

void Unk_0213b5dc::vfunc_0c() {
    setup(0x245c0, 18);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b610::Unk_0213b610() {
    func_020f80d8(sub);
    id = 41;
}

Unk_0213b610::~Unk_0213b610() {
    func_020f80ac(sub);
}

void Unk_0213b610::vfunc_0c() {
    setup(0x2a824, 19);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

void Unk_0213b610::vfunc_10() {
    Unk_0213b8e8::vfunc_10();
    ((SubObj *)sub)->vfunc_00();
}

void Unk_0213b610::vfunc_28(u32 a, u32 c) {
    if (c >= 99 && c <= 171) {
        func_020f8290(sub, a);
        func_020f80a4(sub, 1);
    } else {
        func_020f80a4(sub, 0);
    }
}

Unk_0213b644::Unk_0213b644() {
    id = 42;
}

Unk_0213b644::~Unk_0213b644() {
}

void Unk_0213b644::vfunc_0c() {
    setup(0x245c0, 20);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b678::Unk_0213b678() {
    id = 43;
}

Unk_0213b678::~Unk_0213b678() {
}

void Unk_0213b678::vfunc_0c() {
    setup(0x245c0, 21);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b6ac::Unk_0213b6ac() {
    id = 44;
}

Unk_0213b6ac::~Unk_0213b6ac() {
}

void Unk_0213b6ac::vfunc_0c() {
    setup(0x245c0, 22);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b6e0::Unk_0213b6e0() {
    id = 45;
}

Unk_0213b6e0::~Unk_0213b6e0() {
}

void Unk_0213b6e0::vfunc_0c() {
    setup(0x245c0, 23);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b714::Unk_0213b714() {
    id = 46;
}

Unk_0213b714::~Unk_0213b714() {
}

void Unk_0213b714::vfunc_0c() {
    setup(0x245c0, 24);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b748::Unk_0213b748() {
    id = 47;
}

Unk_0213b748::~Unk_0213b748() {
}

void Unk_0213b748::vfunc_0c() {
    setup(0x245c0, 25);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b77c::Unk_0213b77c() {
    id = 48;
}

Unk_0213b77c::~Unk_0213b77c() {
}

void Unk_0213b77c::vfunc_0c() {
    setup(0x245c0, 26);
    allocRes4();
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b7b0::Unk_0213b7b0() {
    id = 50;
    func_020f44f0(1);
}

Unk_0213b7b0::~Unk_0213b7b0() {
}

void Unk_0213b7b0::vfunc_0c() {
    setup(0x0, 27);
    allocRes11(3);
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b7e4::Unk_0213b7e4() {
    id = 51;
}

Unk_0213b7e4::~Unk_0213b7e4() {
}

void Unk_0213b7e4::vfunc_0c() {
    setup(0x0, 28);
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
    func_020efab8();
}

void Unk_0213b7e4::vfunc_14() {
    func_020f51b4(data_021f5b80.f30);
    data_021f5b80.f4d = 1;
    setTracks(17);
}

Unk_0213b818::Unk_0213b818() {
    id = 52;
}

Unk_0213b818::~Unk_0213b818() {
}

void Unk_0213b818::vfunc_0c() {
    setup(0x2a824, 29);
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}

Unk_0213b84c::Unk_0213b84c() {
    id = 60;
}

Unk_0213b84c::~Unk_0213b84c() {
}

void Unk_0213b84c::vfunc_0c() {
    setup(0x21ef8, 4);
    allocRes11(2);
    allocRes12();
    func_0210be44(func_020edc88());
    func_020f0838(&data_021f5b80, 143);
    data_021f5b80.f62 = 0;
}

Unk_0213b880::Unk_0213b880() {
    id = 99;
}

Unk_0213b880::~Unk_0213b880() {
}

void Unk_0213b880::vfunc_0c() {
    setup(0x2a824, 29);
    allocRes12();
    func_0210be44(func_020edc88());
    data_021f5b80.f62 = 0;
}
