#!/usr/bin/env python3

###
# Lets a compiled unit of the ARM9 main module own .bss.
#
# The main module has no .bss of its own: the zero-initialised objects of its files are the first part of the
# bss-only autoload `autoload_3`. A dsd unit belongs to one module, and `dsd lcf` refuses a source file that is listed
# in two delinks.txt files ("Delink file name ... already used"). So the bss part of a main unit is listed in
# config/<version>/arm9/autoload_3/delinks.txt under a placeholder name, the unit's own name with `.bss` before the
# extension:
#
#     config/usa/arm9/delinks.txt                  config/usa/arm9/autoload_3/delinks.txt
#         src/main/unk_0209c37c.cpp:                   src/main/unk_0209c37c.bss.cpp:
#             complete                                     complete
#             .text  start:0x0209c37c end:0x0209c390       .bss   start:0x021d7168 end:0x021d726c
#
# The placeholder has no source file. dsd splits the autoload's gap object at the placeholder's range and writes
# `unk_0209c37c.bss.o(.bss)` between the two gap pieces in the linker script. This tool, which runs right after
# `dsd lcf`, renames that selector to the real object, `unk_0209c37c.o(.bss)`, and removes the placeholder from the
# list of objects to link, so the .bss sections of the main unit's object land in autoload_3 at the placeholder's
# range. Nothing else changes; without a placeholder unit the step is not part of the build.
#
# The same convention works for any module pair (the placeholder may be listed in any delinks.txt). It is used for
# main/autoload_3 and for the library modules autoload_2 and itcm, whose bss is in autoload_3 too; their units may
# be C files (`src/autoload_2/unk_0210f0c4.bss.c` stands for the bss of `src/autoload_2/unk_0210f0c4.c`).
#
# Usage:
#   python3 tools/bss_units.py build/usa/objects.txt build/usa/arm9.lcf --config config/usa/arm9 \
#       -o build/usa/arm9_bss_units.lcf --objects-out build/usa/objects_bss_units.txt
###

import argparse
import re
import sys
from pathlib import Path

SUFFIX = ".bss"


def placeholders(config: Path) -> list[tuple[Path, str]]:
    '''(delinks.txt, placeholder source) of every placeholder unit in the config'''
    found = []
    for delinks in sorted(config.rglob("delinks.txt")):
        for line in delinks.read_text().splitlines():
            if line and not line[0].isspace() and line.rstrip().endswith(":"):
                source = line.rstrip()[:-1].strip()
                if Path(source).with_suffix("").suffix == SUFFIX:
                    found.append((delinks, source))
    return found


def real_source(placeholder: str) -> str:
    path = Path(placeholder)
    return str(path.with_name(path.with_suffix("").with_suffix("").name + path.suffix))


def unit_names(delinks: Path) -> dict[str, bool]:
    '''{source: complete} for every unit of a delinks.txt'''
    units = {}
    current = None
    for line in delinks.read_text().splitlines():
        if line and not line[0].isspace() and line.rstrip().endswith(":"):
            current = line.rstrip()[:-1].strip()
            units[current] = False
        elif current and line.strip() == "complete":
            units[current] = True
    return units


def process(lcf: str, objects: list[str], config: Path) -> tuple[str, list[str]]:
    all_units = {}
    for delinks in config.rglob("delinks.txt"):
        all_units.update(unit_names(delinks))
    for delinks, placeholder in placeholders(config):
        source = real_source(placeholder)
        if not all_units.get(placeholder):
            sys.exit(f"bss_units.py: {delinks}: {placeholder} must be marked complete")
        if not all_units.get(source):
            sys.exit(f"bss_units.py: {delinks}: {placeholder} is the bss of {source}, which is not a complete unit of "
                     f"any delinks.txt")
        stem = Path(source).with_suffix("").name
        pattern = re.compile(r"^([ \t]*)" + re.escape(stem + SUFFIX) + r"\.o\(\.bss\)[ \t]*$", re.M)
        if len(pattern.findall(lcf)) != 1:
            sys.exit(f"bss_units.py: the linker script has no single '{stem}{SUFFIX}.o(.bss)' line for {placeholder}")
        lcf = pattern.sub(lambda m: f"{m[1]}{stem}.o(.bss)", lcf)
    # dsd lists the placeholder's object under the real object's name or under its own, depending on the version
    kept = []
    for line in objects:
        path = Path(line.strip().strip('"'))
        if path.with_suffix("").suffix == SUFFIX or line in kept:
            continue
        kept.append(line)
    return lcf, kept


def main() -> None:
    parser = argparse.ArgumentParser(description="Gives main units their .bss range in autoload_3")
    parser.add_argument("objects_file", type=Path, help="objects.txt generated by dsd lcf")
    parser.add_argument("lcf", type=Path, help="Linker script generated by dsd lcf")
    parser.add_argument("--config", type=Path, required=True, help="dsd config directory, e.g. config/usa/arm9")
    parser.add_argument("-o", type=Path, dest="out", required=True, help="Output linker script")
    parser.add_argument("--objects-out", type=Path, required=True, help="Output list of objects to link")
    args = parser.parse_args()
    lcf, objects = process(args.lcf.read_text(), args.objects_file.read_text().splitlines(), args.config)
    args.out.write_text(lcf)
    args.objects_out.write_text("\n".join(objects) + "\n")


if __name__ == "__main__":
    main()
