#!/usr/bin/env python3

###
# Adds a FORCE_ACTIVE block to the linker script, with one global symbol in every section of every delinked object.
#
# The original game was linked with dead-stripping, which removed unused functions such as the base-object
# constructor and destructor variants (C2, D2) that mwcc emits for C++ classes. We link with dead-stripping too, but
# delinked code has to be kept even when nothing references it, e.g. overlays that are only loaded by ID.
# mwldarm's -force_active option crashes under wibo, so the symbols go in the linker script instead.
#
# Usage:
#   python3 tools/force_active.py build/usa/objects.txt build/usa/arm9.lcf -o build/usa/arm9_force_active.lcf
###

import argparse
import re
import struct
from pathlib import Path

SHT_SYMTAB = 2
STB_GLOBAL = 1
SHN_UNDEF = 0
SHN_LORESERVE = 0xff00


def section_symbols(path: Path) -> list[str]:
    '''Returns the lowest-addressed global symbol defined in each section of an ELF object'''
    data = path.read_bytes()
    (e_shoff,) = struct.unpack_from("<I", data, 0x20)
    e_shentsize, e_shnum = struct.unpack_from("<HH", data, 0x2e)
    sections = [struct.unpack_from("<10I", data, e_shoff + i * e_shentsize) for i in range(e_shnum)]
    first = {}
    for _, type, _, _, offset, size, link, _, _, _ in sections:
        if type != SHT_SYMTAB:
            continue
        strtab = sections[link]
        for i in range(0, size, 16):
            name, value, _, info, _, shndx = struct.unpack_from("<IIIBBH", data, offset + i)
            if info >> 4 != STB_GLOBAL or shndx == SHN_UNDEF or shndx >= SHN_LORESERVE:
                continue
            start = strtab[4] + name
            symbol = data[start:data.index(b"\0", start)].decode()
            if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", symbol):
                # Not an identifier in linker scripts, e.g. .p__sinit_* in .ctor, which KEEP_SECTION keeps anyway
                continue
            if shndx not in first or value < first[shndx][0]:
                first[shndx] = (value, symbol)
    return [symbol for _, symbol in first.values()]


def main() -> None:
    parser = argparse.ArgumentParser(description="Adds FORCE_ACTIVE for every delinked object's sections to an LCF")
    parser.add_argument("objects_file", type=Path, help="objects.txt generated by dsd lcf")
    parser.add_argument("lcf", type=Path, help="Linker script generated by dsd lcf")
    parser.add_argument("-o", type=Path, dest="out", required=True, help="Output linker script")
    args = parser.parse_args()

    symbols = []
    for line in args.objects_file.read_text().splitlines():
        path = Path(line.strip().strip('"'))
        if "delinks" in path.parts:
            symbols += section_symbols(path)

    lcf = args.lcf.read_text()
    block = "FORCE_ACTIVE {\n    " + ",\n    ".join(symbols) + "\n}\n\n"
    assert "KEEP_SECTION {" in lcf
    args.out.write_text(lcf.replace("KEEP_SECTION {", block + "KEEP_SECTION {", 1))


if __name__ == "__main__":
    main()
